

INSERT INTO `backlink` ( `Name_BackLink`, `Url_BackLink`, `Type_BackLink`) VALUES
( 'mapquest', 'https://mapquest.com/', 'Maps & Local'),
( 'askmap', 'http://www.askmap.net/', 'Maps & Local'),
( 'place123', 'http://www.place123.net/', 'Maps & Local'),
( 'uebermaps', 'https://uebermaps.com/', 'Maps & Local'),
( 'citybyapp', 'https://www.citybyapp.com/', 'Maps & Local'),
( 'iglobal', 'https://www.iglobal.co/', 'Maps & Local'),
( 'freead1', 'https://freead1.net/', 'Classified Ads'),
( 'expatriates', 'https://www.expatriates.com/', 'Classified Ads'),
( 'qwikad', 'https://qwikad.com/', 'Classified Ads'),
( 'adlandpro', 'http://www.adlandpro.com/', 'Classified Ads'),
( 'adsyellowpages', 'http://www.adsyellowpages.com/', 'Classified Ads'),
( 'classifieds.justlanded', 'https://classifieds.justlanded.com/en/', 'Classified Ads'),
( 'pinterest', 'https://www.pinterest.com/', 'Images'),
( 'flickr', 'https://www.flickr.com', 'Images'),
( 'create.piktochart', 'https://create.piktochart.com/', 'Images'),
( '500px', 'https://500px.com/', 'Images'),
( 'trover', 'https://www.trover.com/', 'Images'),
( 'pbase', 'https://pbase.com/', 'Images'),
( 'photopeach', 'https://photopeach.com/', 'Images'),
( 'mobypicture', 'http://www.mobypicture.com/', 'Images'),
( '23hq', 'http://www.23hq.com/', 'Images'),
( 'pexels', 'https://www.pexels.com/', 'Profiles'),
( 'ted', 'https://www.ted.com', 'Profiles'),
( 'mixcloud', 'https://www.mixcloud.com/', 'Profiles'),
( 'dealspotr', 'https://dealspotr.com/', 'Profiles'),
( 'coolors', 'https://coolors.co/', 'Profiles'),
( 'bonanza', 'https://www.bonanza.com/', 'Profiles'),
( 'hubpages', 'https://hubpages.com/', 'Profiles'),
( 'about', 'https://about.me/', 'Profiles'),
( 'visual', 'https://visual.ly/', 'Profiles'),
( 'snupps', 'https://www.snupps.com/', 'Profiles'),
( 'pearltrees', 'https://www.pearltrees.com/', 'Social Bookmarking'),
( 'scoop', 'https://www.scoop.it/', 'Social Bookmarking'),
( 'list', 'https://list.ly/', 'Social Bookmarking'),
( 'podbean', 'https://podbean.com/', 'Social Bookmarking'),
( 'diigo', 'https://www.diigo.com/', 'Social Bookmarking'),
( 'instapaper', 'https://www.instapaper.com/', 'Social Bookmarking'),
( '4mark', 'http://www.4mark.net/', 'Social Bookmarking'),
( 'reddit', 'https://old.reddit.com/', 'Social Bookmarking'),
( 'video-bookmark', 'http://www.video-bookmark.com', 'Social Bookmarking'),
( 'socialbookmarkssite', 'http://www.socialbookmarkssite.com/', 'Social Bookmarking'),
( 'write', 'https://www.write.as', 'Premium Blogging'),
( 'livejournal', 'https://www.livejournal.com', 'Premium Blogging'),
( 'medium', 'https://www.medium.com', 'Premium Blogging'),
( 'edublogs', 'https://www.edublogs.com', 'Premium Blogging'),
( 'decor2day', 'https://decor2day.com/redirect.php', 'Google Links'),
( 'sites.google', 'https://www.sites.google.com', 'Google Links');
